
  name: CI
  
  on:
    push:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
    pull_request:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0.x'  # Ajusta la versión según tus necesidades

        - name: Install Android SDK
          run: |
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
            unzip -q android-sdk.zip -d $HOME/android-sdk
            echo "export ANDROID_HOME=$HOME/android-sdk" >> $HOME/.bashrc
            echo "export PATH=$PATH:$HOME/android-sdk/tools/bin:$HOME/android-sdk/platform-tools" >> $HOME/.bashrc

        - name: Accept Android SDK licenses
          run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        - name: Install .NET MAUI workload for Android
          run: dotnet workload install maui-android
  
        - name: Restore dependencies
          run: dotnet restore
  
        - name: Build
          run: dotnet build --configuration Release
  
        - name: Run unit tests
          run: dotnet test --configuration Release --no-build
  
        - name: Code style check
          run: dotnet tool install -g dotnet-format && dotnet format --check
  
        - name: Ejecutar pruebas
          run: echo "Ejecutando pruebas..."
  
        - name: Desplegar si las pruebas pasan
          run: echo "Desplegando..."
          if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  
        - name: Validar rama de pull request
          run: |
            if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.base_ref }} == 'Development' ]]; then
              if [[ ${{ github.head_ref }} != 'feature/'* && ${{ github.head_ref }} != 'fixbug/'* ]]; then
                echo "No se permiten pull requests desde la rama 'development' a menos que provengan de 'feature/*' o 'fixbug/*'"
                exit 1
              fi
            fi
