
  name: CI
  
  on:
    push:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
    pull_request:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4.1.1

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0'  # Ajusta la versión según tus necesidades

        - name: Install .NET MAUI
          run: dotnet workload install maui-android

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build RutaSeguimientoApp.csproj -c release -f net8.0-android --no-restore
  
        - name: Desplegar si las pruebas pasan
          run: echo "Desplegando..."
          if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  
        - name: Validar rama de pull request
          run: |
            if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.base_ref }} == 'Development' ]]; then
              if [[ ${{ github.head_ref }} != 'feature/'* && ${{ github.head_ref }} != 'fixbug/'* ]]; then
                echo "No se permiten pull requests desde la rama 'development' a menos que provengan de 'feature/*' o 'fixbug/*'"
                exit 1
              fi
            fi
