
  name: CI
  
  on:
    push:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
    pull_request:
      branches:
        - 'Development'
        - 'feature/*'
        - 'fixbug/*'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4.1.1

        - name: MAUIAppVersion
          uses: managedcode/MAUIAppVersion@v1
          with:
            csproj: 'path/to/my-project.csproj'
            version: ${{ github.run_number }} # to keep value unique
            displayVersion: '1.0.0'
            printFile: true # optional
        
        - name: Desplegar si las pruebas pasan
          run: echo "Desplegando..."
          if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  
        - name: Validar rama de pull request
          run: |
            if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.base_ref }} == 'Development' ]]; then
              if [[ ${{ github.head_ref }} != 'feature/'* && ${{ github.head_ref }} != 'fixbug/'* ]]; then
                echo "No se permiten pull requests desde la rama 'development' a menos que provengan de 'feature/*' o 'fixbug/*'"
                exit 1
              fi
            fi
